function estOffset(dateObj){var mo=dateObj.getMonth()+1;
if(mo<3||mo>11){return 300;
}if(mo>3&&mo<11){return 240;
}var today=dateObj.getDate();
var firstSunday=(today-dateObj.getDay())%7;
if(firstSunday<=0){firstSunday=firstSunday+7;
}if(mo==3){var secondSunday=firstSunday+7;
return(today>secondSunday||(today==secondSunday&&dateObj.getHours()>=2))?240:300;
}else{return(today>firstSunday||(today==firstSunday&&dateObj.getHours()>=2))?300:240;
}}if(typeof estNow=="undefined"||typeof estNowWithYear=="undefined"){var estNow=new Date();
var estNowInMillis=estNow.getTime();
var millisFromEST=(estNow.getTimezoneOffset()-estOffset(estNow))*60000;
var estNow=new Date(estNowInMillis+millisFromEST);
var estNowWithYear=estNow.getYear();
var estNowWithYear=(estNowWithYear<1900)?estNowWithYear+1900:estNowWithYear;
estNowWithYear=dateToString(estNow).toString();
}window.cNodeExists=function(){return typeof commercialNode!=="undefined"&&commercialNode!==""&&commercialNode?commercialNode:false;
};
wpniAds=new Object();
if(typeof wpniSite=="undefined"){wpniSite="";
}if(typeof wpniDomain=="undefined"){wpniDomain=document.domain.split(".")[1]+"."+document.domain.split(".")[2];
}wpniAds=new Object();
wpniAds.keyvalues=new Object();
wpniAds.adTypes=new Object();
wpniAds.utils=new Object();
wpniAds.deliveryType=new Object();
wpniAds.templates=new Object();
wpniAds.templates.rules=new Object();
wpniAds.templates.initRule=function(ruleName){this.rules[ruleName]=new Object();
this.rules[ruleName].where=new Array("");
this.rules[ruleName].when=new Array("");
this.rules[ruleName].what=new Array("");
};
wpniAds.utils.wabs=new Object();
wpniAds.utils.wabs.recalc=function(){var rootElement=(document.compatMode!="BackCompat")?document.documentElement:document.body;
this.bodyheight=rootElement.scrollHeight;
this.bodywidth=rootElement.scrollWidth;
this.scrollheight=rootElement.scrollTop;
this.scrollwidth=rootElement.scrollLeft;
this.windowheight=rootElement.clientHeight;
this.windowwidth=rootElement.clientWidth;
};
function trimAll(sString,toTrim){if(typeof sString=="undefined"||!sString){return"";
}while(sString.substring(0,1)==toTrim){sString=sString.substring(1,sString.length);
}while(sString.substring(sString.length-1,sString.length)==toTrim){sString=sString.substring(0,sString.length-1);
}return sString;
}function pageId(){var pageIdStringRoot=(typeof pageIdRoot!="undefined")?pageIdRoot:wpniSite;
if(typeof this.returnValue=="undefined"){this.pIdReturnValue=location.href.split("?")[0];
if(this.pIdReturnValue.lastIndexOf(".")>this.pIdReturnValue.lastIndexOf("/")){this.pIdReturnValue=this.pIdReturnValue.substring(0,this.pIdReturnValue.lastIndexOf("."));
}if(this.pIdReturnValue.lastIndexOf("index")>this.pIdReturnValue.lastIndexOf("/")||this.pIdReturnValue.lastIndexOf("default")>this.pIdReturnValue.lastIndexOf("/")){this.pIdReturnValue=this.pIdReturnValue.substring(0,this.pIdReturnValue.lastIndexOf("/"));
}this.pIdReturnValue=this.pIdReturnValue.split(document.domain)[1];
this.pIdReturnValue=trimAll(this.pIdReturnValue,"/");
this.pIdReturnValue=this.pIdReturnValue.replace(/[\/\.]/gi,"-");
this.pIdReturnValue=unescape(this.pIdReturnValue);
if(this.pIdReturnValue==""){this.pIdReturnValue=pageIdStringRoot;
}}return"pageId="+pageIdStringRoot+"-"+this.pIdReturnValue.replace(/[^a-z0-9_-]/gi,"")+";";
}function getCookie(name){var cookie=" "+document.cookie;
var search=" "+name+"=";
var setStr=null;
var offset=0;
var end=0;
if(cookie.length>0){offset=cookie.indexOf(search);
if(offset!=-1){offset+=search.length;
end=cookie.indexOf(";",offset);
if(end==-1){end=cookie.length;
}setStr=unescape(cookie.substring(offset,end));
}}return(setStr);
}function setCookie(name,value,expires,path,domain,secure){cookieString=name+"="+escape(value)+((expires)?"; expires="+expires:"")+((path)?"; path="+path:"")+((domain)?"; domain="+domain:"")+((secure)?"; secure":"");
if(location.href.match("test_cookie")){adOpsDebug("<b>domain passed to setCookie:</b> "+domain+"<br/>");
}document.cookie=cookieString;
}var adOpsLocalFlag=(getCookie("WPATC")&&getCookie("WPATC").match("C=1:"))?true:false;
function adopsDebugToggle(){var toggleButton=document.getElementById("adopsDebugToggle");
var adopsDebugDiv=document.getElementById("adopsDebugDiv");
adopsDebugDiv.style.display=(toggleButton.innerHTML=="Show Data")?"block":"none";
toggleButton.innerHTML=(toggleButton.innerHTML=="Show Data")?"Hide Data":"Show Data";
}function adopsDebug(_str){if(!urlCheck("debugAdCode",{parent:true})&&!urlCheck("adopsDebug",{parent:true})){return ;
}if(!document.getElementById("adopsDebugDiv")){debugDiv=document.createElement("DIV");
debugDiv.style.fontSize="9px";
debugDiv.style.textAlign="left";
debugDiv.style.fontFamily="verdana,arial,helvetica";
debugDiv.style.padding="10px";
debugDiv.style.marginBottom="10px";
debugDiv.style.borderBottom="1px solid #a8a1a1";
debugDiv.style.backgroundColor="#e1e1e8";
debugDiv.innerHTML="<p style='margin:0px 0px 5px 0px;padding:0px;font-size:14px;color:#272127'>WPNI AdOps Debug Info&nbsp;<a href='javascript:adopsDebugToggle()' style='font-weight:bold;font-size:10px' id='adopsDebugToggle'>Show Data</a></p>";
debugDivContent=document.createElement("DIV");
debugDivContent.setAttribute("id","adopsDebugDiv");
debugDivContent.style.display="none";
debugDiv.appendChild(debugDivContent);
document.body.insertBefore(debugDiv,document.body.firstChild);
}document.getElementById("adopsDebugDiv").innerHTML+=_str;
}function debugTextArea(ac,adAddress){if(!urlCheck("debugAdCode",{parent:true})&&adAddress){return ;
}var bgColor=(adAddress)?"FFAA00":"D9CCFF";
var color=(adAddress)?"770000":"5B24FF";
var debugLink="";
var debugPre='<div style="position:relative;float:left;z-index:1000000000">';
if(!adAddress){possAdIds=ac.match(/[^\d]\d{7,9}[^\d]/gi);
if(possAdIds){var newPAI=new Array();
for(var a=0;
a<possAdIds.length;
a++){var addFlag=true;
var stripped=possAdIds[a].substring(1,possAdIds[a].length-1);
for(var b=0;
b<newPAI.length;
b++){if(stripped==newPAI[b]){addFlag=false;
break;
}}if(addFlag){newPAI.push(stripped);
}}debugLink='<div style="color:#000000;font-weight:bold;text-decoration:none"><em>Possible</em> Ad Ids: '+((newPAI.length>0)?(newPAI):("<em>NONE</em>"))+"</div>";
}}else{debugLink='<div><a style="color:#111177;font-weight:bold;text-decoration:none" target="_blank" href="'+adAddress.replace(/adj/gi,"/adi/")+'">Click Here To See The Ad Call In Its Own Window</a></div>';
}var debug='<div style="text-align:left;text-transform:none;letter-spacing:normal;line-spacing:normal;padding:8px;position:absolute:top:0px;left:0px;width:300px;background-color:#'+bgColor+";color:#"+color+';font-family:verdana;font-size:9px;word-wrap:break-word;text-wrap:unrestricted;overflow:scroll">'+debugLink+textifyCode(ac)+"</div>";
var debugPost="</div>";
var debugReturn=debugPre+debug+debugPost;
if(adAddress){document.write(debugReturn);
}return debugReturn;
}function postLoadDebug(){scripts=document.getElementsByTagName("script");
for(var a=0;
a<scripts.length;
a++){if(scripts[a].innerHTML.match("placeAd")&&scripts[a].parentNode.nodeName.toLowerCase()!="head"){scripts[a].parentNode.innerHTML+=debugTextArea(scripts[a].parentNode.innerHTML,null);
}}}wpniAds.addScript=function(b){var a=document.createElement("script");
a.type="text/javascript";
a.src=b;
document.getElementsByTagName("head")[0].appendChild(a);
};
wpniAds.addCss=function(b){var a=document.createElement("style");
a.type="text/css";
a.styleSheet?a.styleSheet.cssText=b:a.appendChild(document.createTextNode(b));
document.getElementsByTagName("head")[0].appendChild(a);
};
function getQSValue(name){var locString=(arguments[1])?arguments[1]:window.location.href;
var regex=new RegExp("[\\?&;]"+name);
var results=regex.exec(locString);
if(!results){return null;
}var regex=new RegExp("[\\?&;]"+name+"=([^&#]*)");
var results=regex.exec(locString);
return(results==null)?"":results[1];
}function urlCheck(arg){var loc="";
try{loc=parent.window.location.href;
}catch(e){loc=document.referrer;
}if(arguments[1]&&typeof arguments[1]=="object"){var obj=arguments[1];
var regex=(obj.type=="variable")?new RegExp("[\\?&;]"+arg+"=([^&#?]*)"):new RegExp(arg);
}else{var regex=new RegExp(arg);
}var results=regex.exec(loc);
return(results==null)?null:results[results.length-1];
}function innovations_kv(){var a=urlCheck("ad",{type:"variable"});
if(a&&a=="inw"){return"inw=y;";
}if(a&&a=="ins"){return"ins=y;";
}return"";
}function doubleClickTestCode(testFlagArray){if(typeof this.dctCodeValue=="undefined"){this.dctCodeValue="";
var queryResult=urlCheck("test_ads",{type:"variable"});
this.dctCodeValue=(queryResult&&queryResult!="")?"kw=test_"+queryResult+";":"";
}return this.dctCodeValue;
}function timeScope(){numPop=(typeof numPop=="undefined")?5:numPop;
hourScope=(typeof hourScope=="undefined")?24:hourScope;
var finalNumOfPops=(numPop-1)*2;
var returnValue24=true;
if(getCookie("popUpClockCookie")){if(parseInt(getCookie("popUpClockCookie"))>finalNumOfPops){var returnValue24=false;
}else{setCookie("popUpClockCookie",""+(parseInt(getCookie("popUpClockCookie"))+1)+"",cookieExpStringMaker((hourScope*60*60*1000),thisDate()),"/",wpniDomain,"");
}}else{setCookie("popUpClockCookie","1",""+cookieExpStringMaker((hourScope*60*60*1000),thisDate())+"","/",wpniDomain,"");
}return returnValue24;
}function didntSeePopUpOnPreviousPage(){var returnValuePrev=true;
if(getCookie("popUpOnPreviousPageCookie")!=null){if(getCookie("popUpOnPreviousPageCookie")=="true"){var returnValuePrev=false;
setCookie("popUpOnPreviousPageCookie","false","","/",wpniDomain,"");
}else{setCookie("popUpOnPreviousPageCookie","true","","/",wpniDomain,"");
}}else{setCookie("popUpOnPreviousPageCookie","true","","/",wpniDomain,"");
}return returnValuePrev;
}function isAnyOfTheseInTheUrl(){var returnValue=false;
for(var x=0;
x<arguments.length;
x++){if(location.href.match(arguments[x])){returnValue=true;
}}return returnValue;
}function canHaveInterstitial(wpniDomain){var a="wp_pageview",b=getCookie(a),c=true,d=new Date(parseInt(new Date().getTime())+43200000).toString();
if(b&&b!==""){c=(Number(b)/3).toString().match(/\./)?false:true;
setCookie(a,Number(b)+1,d,"/",wpniDomain);
}else{setCookie(a,"1",d,"/",wpniDomain);
}return c;
}function new_interstitial(b){if(!document.cookie||document.cookie===""){return"";
}var c=typeof tileThatGetsDcopt==="undefined"?1:tileThatGetsDcopt,a=b&&b===c?canHaveInterstitial(wpniDomain):false,d=isAnyOfTheseInTheUrl("no_interstitials","digg=1","yahoo=y","reload=true"),e=document.referrer.match("stumbleupon.com"),f=cNodeExists()==="admin/errorpage";
return a&&b&&b===c&&!d&&!e&&!f?"ad=interstitial;":"";
}function interstitial(){if(cNodeExists()==="admin/errorpage"){return"";
}if(typeof tileThatGetsDcopt!="undefined"&&!tileThatGetsDcopt){return"";
}if(typeof tileThatGetsDcopt=="undefined"){tileThatGetsDcopt=1;
}if((typeof this.intReturnValue=="undefined"&&!isAnyOfTheseInTheUrl("no_interstitials","digg=1","yahoo=y")&&arguments[1]==tileThatGetsDcopt)&&!document.referrer.match("stumbleupon.com")){this.intReturnValue="dcopt=ist;";
if(!isAnyOfTheseInTheUrl("g=1","o=","sid=","reload=true")&&document.domain.match(wpniDomain)){var a=timeScope();
var b=didntSeePopUpOnPreviousPage();
adopsDebug("Interstitial Time Scope: "+a+"<br>Didn't See Pops On Previous Page: "+b+"<br>");
if(a&&b){this.intReturnValue+="ad=pop;";
}}return this.intReturnValue;
}return"";
}var wp_quantcast={exec:function(j){wpniAds.addScript("http://pixel.quantserve.com/seg/"+j+".js");
wp_quantcast._quantsegs();
},_quantgc:function(n){var c=document.cookie;
if(!c){return"";
}var i=c.indexOf(n+"=");
if(-1==i){return"";
}var len=i+n.length+1;
var end=c.indexOf(";",len);
return c.substring(len,end<0?c.length:end);
},_quantsegs:function(){quantSegs="";
var _qsegs=wp_quantcast._quantgc("__qseg").split("|");
for(var i=0;
i<_qsegs.length;
i++){var qArr=_qsegs[i].split("_");
if(qArr.length>1){quantSegs+=("qcseg="+qArr[1]+";");
}}},init:function(){return(typeof quantSegs!="undefined"&&quantSegs!=="")?quantSegs:"";
}};
function revsci(){if(typeof getCookie=="undefined"||!getCookie("rsi_segs")||getCookie("rsi_segs")==""){return"";
}var rs_arr=getCookie("rsi_segs").split("|");
var rs="";
for(var i=0;
i<rs_arr.length;
i++){rs+="rs="+rs_arr[i].replace("J05531_","j")+";";
}return rs;
}function randomInt(top){return Math.floor(Math.random()*top);
}function ordMaker(){if(typeof ord_override!="undefined"&&ord_override){this.ordReturnValue="";
ord_override=false;
}if(typeof this.ordReturnValue=="undefined"||this.ordReturnValue==""){this.ordReturnValue="ord="+randomInt(1000000000000000000);
}return this.ordReturnValue;
}function ajaxOrdMaker(){var ajax_ord="";
if(arguments[0]=="AJAX"){ajax_ord="ajax_ord="+randomInt(10000000000)+";";
}return ajax_ord;
}function maxDim(_obj){var lcSize=_obj.size.toLowerCase();
var dimArray=lcSize.split(",");
var maxWidth=0;
var maxHeight=0;
for(var a=0;
a<dimArray.length;
a++){maxWidth=Math.max(dimArray[a].split("x")[0],maxWidth);
maxHeight=Math.max(dimArray[a].split("x")[1],maxHeight);
}return[maxWidth,maxHeight];
}function dfpCompFunc(){if(typeof this.dfpReturnValue=="undefined"||this.dfpReturnValue==""){if(typeof dfpcomp!="undefined"){this.dfpReturnValue="dfpcomp="+dfpcomp+";";
}else{this.dfpReturnValue="";
}}return this.dfpReturnValue;
}function wpFlex(size){return"sz="+size+";";
}function poe(){if(typeof this.poeReturnValue=="undefined"){poeString=wpniSite+"_poe";
this.poeReturnValue="poe=no;";
if(getCookie(poeString)==null||getCookie(poeString)=="false"){this.poeReturnValue="poe=yes;";
setCookie(poeString,"true","","/","","");
}}return this.poeReturnValue;
}function rss(){if(typeof rssString=="undefined"){return"";
}if(typeof this.rssReturnValue=="undefined"){if(location.href.indexOf(rssString)!=-1){this.rssReturnValue="fromrss=y;";
setCookie("rss_now","true","","/",wpniDomain,"");
setCookie("rss","true",""+cookieExpStringMaker((28*24*60*60*1000),thisDate())+"","/",wpniDomain,"");
}else{this.rssReturnValue="fromrss=n;";
setCookie("rss_now","false",""+cookieExpStringMaker((28*24*60*60*1000),thisDate())+"","/",wpniDomain,"");
}if(getCookie("rss")!=null){this.rssReturnValue+="rss=y;";
}else{this.rssReturnValue+="rss=n;";
}}return this.rssReturnValue;
}function heavy(){if(typeof this.heavyReturnValue=="undefined"){this.heavyReturnValue="heavy=n;";
if(typeof document.referrer!="undefined"){if(document.referrer==""){this.heavyReturnValue="heavy=y;";
}}}return this.heavyReturnValue;
}function charToCodeAt(str){var new_str="";
var str_length=str.length;
for(var j=0;
j<str_length;
j++){new_str+=(str.charAt(j).match(/[^a-zA-Z0-9]/gi))?"_"+str.charCodeAt(j).toString(16):str.charAt(j);
}return new_str;
}function user_id_kv(){return(getCookie("s_vi"))?"u=o*"+charToCodeAt(getCookie("s_vi"))+";":"";
}function tile(tileBoolean,varDcCount,thisPos,delivery){if(!tileBoolean){return ;
}this.tileReturnValue=varDcCount;
if(delivery=="AJAX"){if(typeof AJAXTileArray=="undefined"){this.AJAXTileArray=new Array();
}if(!this.AJAXTileArray[thisPos.slug+delivery]){this.AJAXTileArray[thisPos.slug+delivery]=varDcCount;
}else{this.tileReturnValue=this.AJAXTileArray[thisPos.slug+delivery];
}}return"tile="+this.tileReturnValue+";";
}function cookieExpStringMaker(){var today=new Date();
var todayPlusDay=today.getTime()+arguments[0];
today.setTime(todayPlusDay);
return""+today+"";
}function thisDate(){if(typeof this.dateReturnValue=="undefined"){var estNow=new Date();
var estNowInMillis=estNow.getTime();
var millisFromEST=(estNow.getTimezoneOffset()-estOffset(estNow))*60000;
this.dateReturnValue=new Date(estNowInMillis+millisFromEST);
}return this.dateReturnValue;
}function dateToString(){if(typeof this.dtsReturnValue=="undefined"){var thisDateObj=thisDate();
var yyyy=thisDateObj.getYear();
yyyy+=(yyyy<1900)?1900:0;
var mm=thisDateObj.getMonth()+1;
var dd=thisDateObj.getDate();
var hour=thisDateObj.getHours();
var min=thisDateObj.getMinutes();
if(mm<10){mm="0"+mm;
}if(dd<10){dd="0"+dd;
}if(hour<10){hour="0"+hour;
}if(min<10){min="0"+min;
}this.dtsReturnValue=""+yyyy+mm+dd+hour+min;
}return this.dtsReturnValue;
}function dayOfWeekCheck(now,dosString){if(typeof dosString=="undefined"){return true;
}dosDate=thisDate();
thisDos=dosDate.getDay();
return(dosString.match(thisDos))?true:false;
}function dateCheck(when,now){this.dateCheckReturnValue=false;
if(typeof when=="undefined"||when==""){this.dateCheckReturnValue=true;
}else{dateSets=when.split(";");
for(x=0;
x<dateSets.length;
x++){if(now>=dateSets[x].split("/")[0]&&now<=dateSets[x].split("/")[1]&&dayOfWeekCheck(now,dateSets[x].split("/")[2])){this.dateCheckReturnValue=true;
}}}return this.dateCheckReturnValue;
}function locationCheck(where,currentLoc){if(typeof where=="undefined"||where==""){return true;
}var nodes=where.split(";");
this.locCheckReturnValue=true;
for(var x=0;
x<nodes.length;
x++){if(nodes[x].charAt(0)!="!"){this.locCheckReturnValue=false;
}}for(var x=0;
x<nodes.length;
x++){var posTest=(nodes[x].charAt(0)=="!")?false:true;
nodes[x]=(nodes[x].charAt(0)=="!")?nodes[x].split("!")[1]:nodes[x];
var posRegExp=RegExp(nodes[x],"gi");
var thisLocCheck=(currentLoc.match(posRegExp)||pageId().match(posRegExp));
if(thisLocCheck){if(posTest){this.locCheckReturnValue=true;
}else{this.locCheckReturnValue=false;
break;
}}}return this.locCheckReturnValue;
}function getHighestValue(){var longest=0;
var loop;
for(loop=0;
loop<arguments.length;
loop++){if(arguments[loop]>longest){longest=arguments[loop];
}}return longest;
}function siteZoneDir(currentLoc){var currentLocArray=currentLoc.split("/");
if(wpniSite==""){this.szdReturnValue=currentLoc+";";
}else{this.szdReturnValue=wpniSite+"."+currentLoc+";";
}return this.szdReturnValue;
}function adDelivery(){var deliveryArray=["AJAX","inline","adi"];
var delivery=arguments[0].toString();
for(var d=0;
d<deliveryArray.length;
d++){if(delivery.match(deliveryArray[d])){deliveryType="iframe";
break;
}else{deliveryType="js";
}}return deliveryType;
}function kvAjax(delivery){return"ajax="+((delivery=="AJAX")?"y":"n")+";";
}function socialMediaSite(){var dReferrer=(document.referrer!="")?document.referrer:false;
var smSites=["facebook.com","digg.com","reddit.com","myspace.com","newstrust.net","twitter.com","delicious.com","stumbleupon.com"];
var smCount=smSites.length;
if(dReferrer){for(var a=0;
a<smCount;
a++){if(dReferrer.match(smSites[a])){return"social=y;";
}}}return"";
}function slugDisplay(slug){var alt="alt_"+slug;
var slug="slug_"+slug;
if(document.getElementById(slug)){document.getElementById(slug).style.display="block";
if(document.getElementById(alt)){document.getElementById(alt).style.display="none";
}}else{adopsDebug('<i style="color:#910004;font-weight:bold">Could not find a DIV with the ID of '+slug+"</i><br/>");
}}function AdInstance(){this.when=new Array();
this.where=new Array();
this.isTest=false;
this.managerListLength=0;
this.AJAX=false;
this.debugAction=function(output){return debugTextArea(output);
};
this.dateObject=new Date();
this.now=dateToString(this.dateObject);
this.tile=true;
this.interstitial="dcopt=ist;";
this.doubleClickFlag=true;
this.doubleClickAdType="adj";
this.dcCode=heavy()+pageId()+wp_quantcast.init()+dfpCompFunc()+rss(this.dateObject)+front();
this.templateCheck=function(currentLoc,thisPos){var templateTest=true;
for(a in wpniAds.templates.rules){var totalFlights=Math.max(wpniAds.templates.rules[a].where.length,wpniAds.templates.rules[a].when.length);
for(var b=0;
b<totalFlights;
b++){if(locationCheck(wpniAds.templates.rules[a].where[b],currentLoc)&&dateCheck(wpniAds.templates.rules[a].when[b],dateToString())){for(var c=0;
c<wpniAds.templates.rules[a].what.length;
c++){var posTestFlag=(wpniAds.templates.rules[a].what[c].charAt(0)!="!")?a:false;
var testNoExclam=wpniAds.templates.rules[a].what[c];
var testNoExclam=(testNoExclam.charAt(0)!="!")?testNoExclam:testNoExclam.substring(1,wpniAds.templates.rules[a].what[c].length);
var testRE=RegExp(testNoExclam.toLowerCase(),"gi");
if(thisPos.slug.match(testRE)&&testNoExclam!=""){templateTest=(posTestFlag)?a:false;
adopsDebug("<b>Template Match ["+a+"]:</b> <i>"+posTestFlag+"</i> for <i>"+testRE+"</i><br>");
}}}}}if(!templateTest){adopsDebug('<i style="color:#910004;font-weight:bold">Failed template test</i><br>');
}return templateTest;
};
this.testAction=function(testFlagArray){return doubleClickTestCode(testFlagArray);
};
this.code="";
this.adExecute=function(currentLoc,what,delivery,onTheFly,thisPos,old_ajax){adopsDebug("currentLoc="+currentLoc+"&nbsp;&nbsp; what="+what+"&nbsp;&nbsp; onTheFly="+onTheFly+"&nbsp;&nbsp; thisPos="+thisPos.keyvalue+"&nbsp;&nbsp;deliveryType = "+adDelivery(delivery));
var targetDivId="wpni_adi_"+thisPos.slug;
slugDisplay(thisPos.slug);
var dcAdDelivery="del="+adDelivery(delivery)+";";
var dcMediaServer=(adDelivery(delivery)=="iframe")?"adi":"adj";
adopsDebug("&nbsp;&nbsp;thisPos="+thisPos.keyvalue+"&nbsp;&nbsp;slugId=slug_"+thisPos.slug+"&nbsp;&nbsp;targetDivId="+targetDivId+"&nbsp;&nbsp;deliveryType = "+dcAdDelivery+"&nbsp;&nbsp;dcMediaServer ="+dcMediaServer+"<br>");
if(this.adType=="inline"){var inlineAdGraf=getInlineAdGraf(this);
if(!inlineAdGraf){adopsDebug('<i style="color:#910004;font-weight:bold">It is an inline ad but we couldn\'t find a good space for the inline ad in the container DIV '+this.parentId+".</i><br/>");
return ;
}else{var inlineDiv=document.createElement("div");
inlineDiv.style.width=maxDim(this)[0]+"px";
inlineDiv.style.height=maxDim(this)[1]+"px";
inlineDiv.style.margin="8px 0px";
inlineDiv.id=targetDivId;
document.getElementById(this.parentId).insertBefore(inlineDiv,inlineAdGraf);
if(this.slugURL){inlineAdSlugDiv=document.createElement("div");
inlineAdSlugDiv.id="slug_"+thisPos.slug;
inlineAdSlugDiv.style.marginTop="8px";
inlineAdSlugImg=document.createElement("img");
inlineAdSlugImg.src=this.slugURL;
inlineAdSlugDiv.appendChild(inlineAdSlugImg);
document.getElementById(this.parentId).insertBefore(inlineAdSlugDiv,inlineDiv);
}}}if(delivery=="AJAX"&&!document.getElementById(targetDivId)){adopsDebug('<i style="color:#910004;font-weight:bold">It is an AJAX call but we could not find the target DIV.</i><br/>');
return ;
}if(delivery=="inline"){document.write('<div id="'+targetDivId+'"></div>');
}if(this.doubleClickFlag==true){if(typeof varDcCount=="undefined"){varDcCount=1;
}else{varDcCount++;
}var adAddress="http://ad.doubleclick.net/"+dcMediaServer+"/"+siteZoneDir(currentLoc)+wpFlex(this.size)+"pos="+thisPos.keyvalue+";"+poe()+this.code+this.testAction(this.testFlagArray)+dcAdDelivery+kvAjax(delivery)+innovations_kv()+interstitial(this.interstitial,varDcCount)+new_interstitial(varDcCount)+this.dcCode+socialMediaSite()+ajaxOrdMaker(delivery)+onTheFly+revsci()+user_id_kv()+tile(this.tile,varDcCount,thisPos,delivery)+ordMaker(delivery)+"?";
}if(dcMediaServer=="adi"){iframeObj=document.createElement("iframe");
iframeObj.setAttribute("src",adAddress);
iframeObj.style.width=maxDim(this)[0]+"px";
iframeObj.style.height=maxDim(this)[1]+"px";
iframeObj.setAttribute("marginWidth","0");
iframeObj.setAttribute("marginHeight","0");
iframeObj.setAttribute("frameBorder","0");
iframeObj.setAttribute("scrolling","no");
iframeObj.setAttribute("allowTransparency","true");
iframeObj.style.border="none";
adDivRef=document.getElementById(targetDivId);
if(adDivRef){if(adDivRef.hasChildNodes()){while(adDivRef.childNodes.length>=1){adDivRef.removeChild(adDivRef.firstChild);
}}adDivRef.appendChild(iframeObj);
adopsDebug("<b>"+targetDivId+" Appended Iframe Ad Call:</b> "+textifyCode(adDivRef.innerHTML)+"<br/>");
}}else{var output='<script type="text/javascript" src="'+adAddress+'"><\/script>';
adopsDebug("<b>document-written call:</b> "+textifyCode(output)+"<br>");
debugTextArea(output,adAddress);
document.write(output);
}};
}function dcNodeOverride(){if(urlCheck("dcnode=")){var theUrl=urlCheck("dcnode",{type:"variable"});
}return(typeof theUrl!="undefined"&&theUrl!="")?theUrl:"test";
}function placeAd2(currentLoc,what,delivery,onTheFly){if(location.href.match("no_ads")){return ;
}adopsDebug('<div style="margin-top:10px;font-size:14px;font-weight:bold">placeAd2("'+currentLoc+'","'+what+'","'+delivery+'","'+onTheFly+'")</div>');
if(typeof onTheFly=="undefined"){onTheFly="";
}var currentLoc=hackBin("currentLoc",currentLoc,what,delivery,onTheFly);
var what=hackBin("what",currentLoc,what,delivery,onTheFly);
var delivery=hackBin("delivery",currentLoc,what,delivery,onTheFly);
var onTheFly=hackBin("onTheFly",currentLoc,what,delivery,onTheFly);
var old_ajax=false;
if(what.match("AJAX")){var delivery="AJAX";
var what=what.replace(/AJAX/,"|");
var old_ajax=true;
}var posOverride=what.split("|")[1];
var adType=what.split("|")[0];
var thisPos=posMaker(adType,posOverride,delivery);
if(typeof adClasses=="undefined"){var adClasses=new Array();
}if(typeof adClasses[adType]=="undefined"){adClasses[adType]=initAdType(adType);
}if(adClasses[adType].isTest&&location.href.match("testAdSpots")){adopsDebug('<b style="color:#009900">This is a test spot.</b></br>');
}else{if(adClasses[adType].isTest){adopsDebug('<b style="color:#990000">This is a test spot and there is no "testAdSpots" in the query string, so it did not get rendered.</b>');
}}var testCheck=!adClasses[adType].isTest||location.href.match("testAdSpots");
var tempCheck=adClasses[adType].templateCheck(currentLoc,thisPos);
if(location.href.match("demoAds")){currentLoc=dcNodeOverride();
}var demoCheckQS=urlCheck("demoAds",{type:"variable"});
var demoPos=false;
if(demoCheckQS){demoCheckQS=demoCheckQS.split(";");
for(var a=0;
demoCheckQS[a];
a++){if(thisPos.keyvalue==demoCheckQS[a]){demoPos=true;
adopsDebug('<div style="color:#770077"><b>Test Ad Spot</b></div>');
break;
}}}if(demoPos||(!location.href.match("demoAds")&&tempCheck&&testCheck)||location.href.match("allAds")){var hardcodes=(wpniAds.templates.rules[tempCheck])?wpniAds.templates.rules[tempCheck].hardcodes:false;
if(hardcodes){if(typeof hardcodes=="object"){hardcodes=hardcodes[Math.floor(Math.random()*hardcodes.length)];
}slugDisplay(thisPos.slug);
document.write(hardcodes);
adopsDebug('<div style="color:#770077"><b>Rendered hardcode on behalf of template <i>'+tempCheck+" </i>:</b><br/>"+textifyCode(hardcodes)+"</div>");
}else{adClasses[adType].adExecute(currentLoc,adType,delivery,onTheFly,thisPos,old_ajax);
}}}function posMaker(adType,posOverride,delivery){if(posOverride||delivery=="AJAX"){var returnValue=adType+((posOverride)?"_"+posOverride:"");
}else{if(typeof this.usedSpots=="undefined"){this.usedSpots=new Array();
}if(this.usedSpots[adType]==null){this.usedSpots[adType]=1;
returnValue=adType;
}else{this.usedSpots[adType]++;
returnValue=adType+"_"+this.usedSpots[adType];
}}return{keyvalue:returnValue,slug:returnValue};
}function getInlineAdGraf(thisAdType){var bottom_of_obstacle=0;
if(document.getElementById(thisAdType.obstacleId)){var obstacle=document.getElementById(thisAdType.obstacleId);
var bottom_of_obstacle=obstacle.offsetTop+obstacle.offsetHeight;
}var grafs=document.getElementById(thisAdType.parentId).getElementsByTagName(thisAdType.childElement);
if(bottom_of_obstacle==0&&grafs.length>4){var targetGrafNum=Math.min(Math.ceil(grafs.length/3),4);
adopsDebug('<span style="font-style:bold;font-color:#009900">Found No Obstacle! Putting inline ad after Graf #'+targetGrafNum+"</span><br/>");
return grafs[targetGrafNum];
}else{for(var i=0;
i<grafs.length;
i++){if(grafs[i].offsetTop>bottom_of_obstacle+thisAdType.obstacleMargin&&i<grafs.length-2){adopsDebug('<span style="font-style:bold;font-color:#009900">Cleared an Obstacle! Putting inline ad after Graf #'+i+"</span><br/>");
return grafs[i];
}}}return false;
}function textifyCode(_code){_code=_code.replace(/</gi,"&lt;");
_code=_code.replace(/>/gi,"&gt;");
return _code;
}function front(){return"";
}var render_google_ads=(Math.floor(Math.random()*100)<3||urlCheck("google_ads=true"))?true:false;
googleAds={googleVars:{google_safe:"high",google_ad_client:"ca-pub-6288951389250281",google_ad_output:"js",google_ad_channel:"other",google_skip:0,google_max_num_ads:3,google_ad_section:"default"},nodeHacks:[],hideBox:"",category:{"washingtonpost.com":"6371669258",artsandliving:"5735109925",news:"2349448776",business:"8141504747",education:"1253622235",health:"4413723416",politics:"7918528095",technology:"1064854213",sports:"3662221933",ros:"0903792148",lifestyle:"5735109925",entertainment:"5735109925"},nodeCheck:function(c){var a=wpAds.textlinks.cat_check(c);
a=typeof a!="undefined"?a:"ros";
return googleAds.category[a];
},debug:function(){for(var a in this.googleVars){adopsDebug("<b>"+a+":</b> "+this.googleVars[a]+"<br>");
}return true;
},vertCheck:function(posId1,posId2){wpniAds.utils.wabs.recalc();
var windowHeight=wpniAds.utils.wabs.windowheight,offset1=document.getElementById(posId1).offsetTop,offset2=document.getElementById(posId2).offsetTop;
adopsDebug("<b>"+posId1+" vertical position:</b> "+offset1+"<br>");
adopsDebug("<b>"+posId2+" vertical position:</b> "+offset2+"<br>");
adopsDebug("<b>windowHeight:</b> "+windowHeight+"<br>");
return(offset1-offset2>windowHeight)||(offset2-offset1>windowHeight);
adopsDebug(e+"<br/>");
return ;
},execute:function(cNode,adCount,test){adopsDebug('<b style="font-size:12px">googleAds("'+this.googleVars.google_ad_client+'","'+cNode+'","'+adCount+'",'+test+")</b><br>");
this.googleVars.google_ad_channel=this.nodeCheck(cNode);
this.googleVars.google_max_num_ads=adCount;
this.googleVars.google_adtest=(test)?"on":"off";
for(var a in this.googleVars){eval(a+'="'+this.googleVars[a]+'"');
}if(!document.getElementById("googleBottomBox")||googleAds.vertCheck("googleBottomBox","googleRightBox")){document.write('<div style="clear:both"></div><script type="text/javascript" src="http://media.washingtonpost.com/wp-srv/ad/google_display.js"><\/script>');
this.debug();
this.googleVars.google_skip+=parseInt(adCount);
}else{this.debug();
adopsDebug("<b>Sorry, the divs were too close vertically to render a "+googleAds.hideBox+" adSense box.</b><br>");
}}};
wpniSite="wpni";
wpniDomain="washingtonpost.com";
show_doubleclick_ad=true;
rssString="fromrss=y";
tileThatGetsDcopt=1;
hourScope=24;
numPop=5;
if(!urlCheck("no_ads")){wpniAds.addScript("http://media.washingtonpost.com/wp-srv/ad/textlink_driver.js");
}wp_meta_data=typeof wp_meta_data!="undefined"?wp_meta_data:{};
wpniAds.contentType={AudioStory:"audio",BlogStory:"blog",front:"front",GraphicStory:"graphic",MediaGallery:"photo",PanoStory:"pano",UGCPhotoStory:"ugc",VideoStory:"video"};
wpniAds.zoneBuilder={name:function(){return typeof wp_meta_data.contentName!="undefined"?"/"+this.valid()+wp_meta_data.contentName:"";
},valid:function(){return(wp_meta_data.contentName[0].charAt(0).match(/[^a-z]/gi))?"c":"";
},exec:function(){var a=wp_meta_data.contentType;
a=typeof wpniAds.contentType[a]!="undefined"&&commercialNode!=="washingtonpost.com"?commercialNode+"/"+wpniAds.contentType[a]:typeof commercialNode!="undefined"?commercialNode:"";
a=a.replace(/\s*/g,"");
return a+this.name();
}};
commercialNode=wpniAds.zoneBuilder.exec();
wpniAds.addCSS=function(arg){if(typeof exists=="undefined"||!exists){var a=document.createElement("link");
a.href="http://media.washingtonpost.com"+arg;
a.rel="stylesheet";
a.type="text/css";
document.getElementsByTagName("head")[0].appendChild(a);
exists=true;
}return true;
};
if(typeof wp_quantcast!=="undefined"){wp_quantcast.exec("p-5cYn7dCzvaeyA");
}wpniAds.templates.initRule("defaultTemplate");
wpniAds.templates.rules.defaultTemplate.what=new Array("!336x35","!bigad","!leaderboard_2","!extra_bb","!featurebar","!tiffany_tile","!336x60","!pushdown","!sponsor","!sponsor_realtor","!deal","!marketing","!nav_tile","!nn","!nn_hp","!nn_sidebar","!nn_footer","!nn_rr","!promo","!sponsor_prem_rental","!tooltile");
if(!location.href.match("suppress_fb")){wpniAds.templates.initRule("homepage");
wpniAds.templates.rules.homepage.what=new Array("!leaderboard");
wpniAds.templates.rules.homepage.where=new Array("washingtonpost.com");
wpniAds.templates.initRule("trulia");
wpniAds.templates.rules.trulia.what=new Array("bigbox");
wpniAds.templates.rules.trulia.where=new Array("trulia");
wpniAds.templates.initRule("jobs");
wpniAds.templates.rules.jobs.what=new Array("336x60");
wpniAds.templates.rules.jobs.where=new Array("jobs");
wpniAds.templates.initRule("local_page");
wpniAds.templates.rules.local_page.what=new Array("!leaderboard","!sponsor");
wpniAds.templates.rules.local_page.where=new Array("^metro/front$");
wpniAds.templates.initRule("realestate");
wpniAds.templates.rules.realestate.what=new Array("sponsor_community","sponsor_new_home_builder");
wpniAds.templates.rules.realestate.where=new Array("realestate");
wpniAds.templates.initRule("rentals");
wpniAds.templates.rules.rentals.what=new Array("sponsor_rental","sponsor_prem_rental");
wpniAds.templates.rules.rentals.where=new Array("rentals");
wpniAds.templates.initRule("liveonlineflex");
wpniAds.templates.rules.liveonlineflex.what=new Array("!flex_ss_bb_hp");
wpniAds.templates.rules.liveonlineflex.where=new Array("multimedia/livevideo");
wpniAds.templates.initRule("lf336");
wpniAds.templates.rules.lf336={what:["336x35_top"],where:["realestate"],when:["201103160000/201112312359"]};
wpniAds.templates.initRule("capdish");
wpniAds.templates.rules.capdish={what:["deal"],where:["metro/front","cityguide"],when:[""],hardcodes:'<script type="text/javascript">		(function(){			var a = {"metro":"11","artsandliving/foodanddining":"12","cityguide":"13","cityguide/restaurants":"14","cityguide/bars":"15","cityguide/movies":"16","cityguide/events":"17","cityguide/music":"18","cityguide/museums":"19","cityguide/theater":"20","cityguide/bestbets":"21","cityguide/kidfriendly":"22","cityguide/visitors":"23"};			if(typeof commercialNode!="undefined" && a[commercialNode]){				document.write(\'<sc\'+\'ript type="text/javascript" src="http://files.secondstreetmedia.com/washingtonpost/widget\'+a[commercialNode]+\'.js"></sc\'+\'ript>\');			}		}())	<\/script>'};
wpniAds.templates.initRule("local336x60");
wpniAds.templates.rules.local336x60={what:["336x60"],where:["local/front"],when:["201107250000/201107312359"]};
wpniAds.templates.initRule("capdish2");
wpniAds.templates.rules.capdish2={what:["336x60"],where:(function(){return(typeof estNowWithYear!="undefined"&&estNowWithYear>="201107250000"&&estNowWithYear<="201107312359"?["lifestyle/food/front"]:["lifestyle/food/front","local/front"]);
}()),when:[""],hardcodes:'<script type="text/javascript">		(function(){			var a = {"local/front":"11","lifestyle/food/front":"12"};			if(typeof commercialNode!="undefined" && a[commercialNode]){				document.write(\'<sc\'+\'ript type="text/javascript" src="http://files.secondstreetmedia.com/washingtonpost/widget\'+a[commercialNode]+\'.js"></sc\'+\'ript>\');			}		}())	<\/script>'};
wpniAds.templates.initRule("servicealley");
wpniAds.templates.rules.servicealley={what:["marketing"],where:["blogs/front","local/front","local/trafficandcommuting/front","local/dc-politics/front","local/md-politics/front","local/virginia_politics/front","business/local-business/front","lifestyle/home/front","lifestyle/home_garden","metro/front","metro/traffic","metro/dc/front","metro/md/front","metro/va/front","metro/transportation","metro/local-tools","business/localbusiness/front","artsandliving/homeandgarden/front","realestate","realestate/neighborhoods/front","rentals"],when:[""],hardcodes:'<script type="text/javascript" src="http://www.servicealley.com/javascripts/wapo-widget.js"><\/script>'};
if(urlCheck("test_ads=networknews")){wpniAds.templates.initRule("nn_hp");
wpniAds.templates.rules.nn_hp={what:["nn_hp"],hardcode:'<div id="nn_ad_tile_hp" style="background-color: rgb(153, 153, 153); position: relative; padding: 0px; margin: 0px; height: 20px; width: 190px;"><img src="http://www.washingtonpost.com/wp-srv/images/spacer.gif" width="190" height="20"><div style="position: absolute; top: 5px; left: 5px; color: rgb(255, 255, 255); font-size: 12px; font-family: Arial,Helvetica,sans-serif;">190x20 Test Spot<br></div></div>'};
}wpniAds.templates.initRule("sponsor_links_bt");
wpniAds.templates.rules.sponsor_links_bt={what:["sponsor_links_bt"],where:[""],when:[""],hardcodes:'<script type="text/javascript"> if(render_google_ads) render_google_ads && typeof googleAds!="undefined" && wpniAds.addCSS("/wp-adv/advertisers/google/textlinks/css/google_textlinks.css") && googleAds.execute(commercialNode,3,false);else wpAds.textlinks.init(wp_meta_data.contentType,"bt",commercialNode)<\/script>'};
wpniAds.templates.initRule("sponsor_links_in");
wpniAds.templates.rules.sponsor_links_in={what:["sponsor_links_in"],where:[""],when:[""],hardcodes:'<script type="text/javascript"> if(render_google_ads) render_google_ads && typeof googleAds!="undefined" && wpniAds.addCSS("/wp-adv/advertisers/google/textlinks/css/google_textlinks.css") && googleAds.execute(commercialNode,3,false);else wpAds.textlinks.init(wp_meta_data.contentType,"in",commercialNode)<\/script>'};
wpniAds.templates.initRule("sponsor_links_rr");
wpniAds.templates.rules.sponsor_links_rr={what:["sponsor_links_rr"],where:[""],when:[""],hardcodes:'<script type="text/javascript"> if(render_google_ads) render_google_ads && typeof googleAds!="undefined" && wpniAds.addCSS("/wp-adv/advertisers/google/textlinks/css/google_textlinks.css") && googleAds.execute(commercialNode,2,false);else wpAds.textlinks.init(wp_meta_data.contentType,"rr",commercialNode)<\/script>'};
wpniAds.templates.initRule("topjobs");
wpniAds.templates.rules.topjobs={what:["topjobs"],where:[""],when:[""],hardcodes:'<script type="text/javascript" src="http://media.washingtonpost.com/wp-adv/topjobs3/top_jobs_v3.js"><\/script>'};
wpniAds.templates.initRule("targettile");
wpniAds.templates.rules.targettile={what:["nav_tile"],where:["entertainment","lifestyle","local","metro"],when:[""],hardcodes:'<img src="http://media.washingtonpost.com/wp-adv/advertisers/target/images/target_tile_30x90.gif" onclick="wpniAds.target.exec()" id="target-tile" alt="Target" border="0" width="90" height="29"/><img src="http://ad.doubleclick.net/ad/N3550.WashingtonPost/B5040651.3;sz=1x1;ord='+Math.floor(Math.random()*1000)+'?" border="0" width="1" height="1" alt="" style="display:none" />'};
wpniAds.target={exec:function(){var b=$("#main-nav-wrapper").next(),a=document.createElement("link");
$(a).attr({href:"http://media.washingtonpost.com/wp-adv/advertisers/target/eidos/target.css",rel:"stylesheet",height:"text/css"});
$("head")[0].appendChild(a);
$("#shell").addClass("target");
c=document.createElement("div");
c.id="target";
$(b).append(c);
$(c).html('<div class="close" onclick="javascript:wpniAds.target.close()">close x</div><object type="application/x-shockwave-flash" data="http://media.washingtonpost.com/wp-adv/advertisers/target/TargetGannett_70x22_Click_r08.swf" width="950" height="950" id="target-circular"><param name="movie" value="http://media.washingtonpost.com/wp-adv/advertisers/target/TargetGannett_70x22_Click_r08.swf"/><param name="quality" value="high"/><param name="wmode" value="transparent"/><param name="menu" value="false"/><param name="allowfullscreen" value="false"/><param name="allowScriptAccess" value="always"/></object><img src="http://ad.doubleclick.net/ad/N3550.WashingtonPost/B5040651.2;sz=1x1;ord='+Math.floor(Math.random()*1000)+'?" border="0" width="1" height="1" alt="" style="display:none" />');
},close:function(){$("div#target").remove();
$("div#shell").removeClass("target");
}};
wpniAds.templates.initRule("market_minute");
wpniAds.templates.rules.market_minute={what:["itb"],where:["realestate"],when:[""],hardcodes:'<div style="clear:both;"></div><div class="hrule single grey dotted wp-pad-top wp-pad-bottom"></div><div class="module advertisement-teaser fontcolor-greypurple">Advertisement</div><div style="width:156px;padding:0;margin:0;"><a href="http://ad.doubleclick.net/clk;236932920;29926764;u?http://www.longandfoster.com/Market-Minutes/MarketMinutesReports.aspx" target="_blank" style="text-decoration:none;border:0;color:#464646;"><img src="http://media.washingtonpost.com/wp-adv/advertisers/longfoster/2011/tile/market_minute_logo.png" border="0" height="37" width="156" alt="" /><img src="http://media.washingtonpost.com/wp-adv/advertisers/longfoster/2011/tile/market_minute_graph.png" height="40" width="65" alt="" border="" style="float:left;margin:3px 3px 3px 0" /><div style="font-family:\'Georgia Pro\',Georgia,serif;font-size:12px;color:#464646;text-decoration:none;">How many homes are available now? Get the details on your market.</div></a></div>'};
if(urlCheck("test_ads=applewp")&&navigator.appName==="Netscape"&&!navigator.userAgent.match(/mobile/gi)){wpniAds.addCss("#wpni_adi_leaderboard.slug { background:none;padding:0 }");
wpniAds.templates.initRule("apple");
wpniAds.templates.rules.apple={what:["leaderboard","!tiffany_tile","!flex_bb_hp","!sponsor_links_rr"],where:["washingtonpost.com"],when:[""]};
}if(typeof wp_meta_data!=="undefined"&&wp_meta_data.contentType&&wp_meta_data.contentType[0]==="CompoundStory"&&typeof revsci==="function"&&revsci().match(/j10513|j10186|j10567|j10406|j10303|j10145/)){wpniAds.templates.initRule("bottom_lb_lever");
wpniAds.templates.rules.bottom_lb_lever={what:["leaderboard_2"],where:[""],when:["201107150000/201112312359"]};
}wpniAds.templates.initRule("featuredcondo");
wpniAds.templates.rules.featuredcondo={what:["sponsor_condo"],where:["realestate"],when:["201107150000/201112312359"]};
}function initAdType(what){var thisAdType=new AdInstance();
thisAdType.testFlagArray=new Array("test_ads","test_"+what);
thisAdType.debugFlagArray=new Array("debugAdCode","debug"+what);
thisAdType.dcCode+=orbitFlag()+getWPATCookie()+mediaPage()+realEstateAreaId()+aptco()+locExpSponsor();
switch(what){case"featurebar":thisAdType.size="446x33";
thisAdType.code="ad=fb;";
break;
case"itb":thisAdType.size="1x1";
thisAdType.code="";
break;
case"leaderboard":thisAdType.size="728x90";
thisAdType.code="ad=lb;";
break;
case"bigad":thisAdType.size="1x1";
thisAdType.code="";
break;
case"bigbox":thisAdType.size="300x250";
thisAdType.code="ad=bb;";
break;
case"extra_bb":thisAdType.size="300x250";
thisAdType.code="ad=bb;";
break;
case"skyscraper":thisAdType.size="160x600";
thisAdType.code="ad=ss;";
break;
case"promo":thisAdType.size="200x60";
thisAdType.code="";
break;
case"tiffany_tile":thisAdType.size="200x60,200x80,234x60,290x60,300x45";
thisAdType.code="ad=tiff;";
break;
case"flex_ss_bb_hp":thisAdType.size="160x600,300x250,300x600,336x850";
thisAdType.code="ad=ss;ad=bb;ad=hp;";
break;
case"flex_bb_hp":thisAdType.size="300x250,300x600,336x850";
thisAdType.code="ad=bb;ad=hp;";
break;
case"flex_ss_bb":thisAdType.size="160x600,300x250";
thisAdType.code="ad=ss;ad=bb;";
break;
case"flex_bb_tp":thisAdType.size="300x250,300x600";
thisAdType.code="ad=bb;ad=tp;";
break;
case"flex_re":thisAdType.size="300x250,300x600";
thisAdType.code="ad=bb;ad=tp;";
break;
case"flex":thisAdType.size="336x850";
thisAdType.code="ad=hp;";
break;
case"336x35":thisAdType.size="336x35";
thisAdType.code="ad=336x35;";
break;
case"336x35_top":thisAdType.size="336x35";
thisAdType.code="ad=336x35;";
break;
case"336x60":thisAdType.size="336x60";
thisAdType.code="ad=336x60;";
break;
case"200x50":thisAdType.size="200x50";
thisAdType.code="ad=200x50;";
break;
case"120x240":thisAdType.size="120x240";
thisAdType.code="ad=120x240;";
break;
case"150x60":thisAdType.size="150x60";
thisAdType.code="ad=150x60;";
break;
case"285x29":thisAdType.size="285x29";
thisAdType.code="ad=285x29;";
break;
case"deal":thisAdType.size="1x1";
thisAdType.tile="ad=1x1;";
break;
case"pushdown":thisAdType.size="1x1";
thisAdType.code="";
break;
case"sponsor":thisAdType.size="1x1";
thisAdType.tile="false";
break;
case"inline_bb":thisAdType.size="300x250";
thisAdType.tile="ad=bb;";
break;
case"marketing":thisAdType.size="1x1";
thisAdType.tile="";
break;
case"nav_tile":thisAdType.size="1x1";
thisAdType.tile="";
break;
case"nn":thisAdType.size="1x1";
thisAdType.tile="";
break;
case"nn_hp":thisAdType.size="190x20";
thisAdType.tile="ad=nn_hp;";
wpTiles.nnHasAd();
break;
case"nn_sidebar":thisAdType.size="200x30";
thisAdType.tile="ad=nn_sidebar;";
wpTiles.nnHasAd();
break;
case"nn_footer":thisAdType.size="200x30";
thisAdType.tile="ad=nn_footer;";
wpTiles.nnHasAd();
break;
case"nn_rr":thisAdType.size="200x80";
thisAdType.tile="ad=nn_rr;";
wpTiles.nnHasAd();
break;
case"tooltile":thisAdType.size="1x1";
thisAdType.tile="";
break;
case"topjobs":thisAdType.size="1x1";
thisAdType.tile="";
break;
case"sponsor_links_bt":thisAdType.size="1x1";
thisAdType.tile="";
break;
case"sponsor_links_in":thisAdType.size="1x1";
thisAdType.tile="";
break;
case"sponsor_links_rr":thisAdType.size="1x1";
thisAdType.tile="";
break;
case"sponsor_condo":thisAdType.size="1x1";
thisAdType.tile="";
break;
}return thisAdType;
}function posMaker(adType,posOverride,delivery){if(posOverride||delivery=="AJAX"){var returnValue=adType+((posOverride)?"_"+posOverride:"");
}else{if(typeof this.usedSpots=="undefined"){this.usedSpots=new Array();
}if(this.usedSpots[adType]==null){this.usedSpots[adType]=1;
returnValue=adType;
}else{this.usedSpots[adType]++;
returnValue=adType+"_"+this.usedSpots[adType];
}}var posArray={leaderboard:1,leaderboard_2:2,skyscraper:3,flex_ss_bb_hp:6,flex_bb_hp:6,flex_bb_tp:6,featurebar:7,tiffany_tile:14,"336_35":19,bigbox:20,pushdown:43,extra_bb:44,deal:45};
if(typeof posArray[returnValue]!="undefined"&&(typeof commercialNode!="undefined"&&commercialNode=="metro")){posArray.flex_ss_bb_hp=16;
}if(typeof posArray[returnValue]!="undefined"&&(typeof commercialNode!="undefined"&&commercialNode.match("washingtonpost.com"))){posArray.flex_bb_hp=16;
}if((typeof commercialNode!="undefined"&&commercialNode=="trulia")&&(typeof posArray[returnValue]!="undefined"&&returnValue=="flex_bb_tp")){return{keyvalue:"flex_re",slug:"flex_bb_tp"};
}return{keyvalue:((typeof posArray[returnValue]!="undefined")?"ad"+posArray[returnValue]:returnValue),slug:returnValue};
}function orbitFlag(){return(document.location.href.match("/wp-dyn/")?"orbit=y;":"");
}function mediaPage(){return(typeof thisNode!="undefined"&&thisNode.match(/media|photo|video/)||typeof commercialNode!="undefined"&&commercialNode.match(/media|photo|video/)||urlCheck(/video|gallery|scene-in|mobile/))?"!c=media;":"";
}function getWPATCookie(){if(document.cookie.indexOf("WPATC")!=-1){var start=(document.cookie.indexOf("WPATC")+6);
var end=(document.cookie.indexOf(";",start))==-1?document.cookie.length:document.cookie.indexOf(";",start);
var cookie=document.cookie.substring(start,end)+";";
while(cookie.indexOf(":")!=-1){cookie=cookie.substring(0,cookie.indexOf(":"))+";"+cookie.substring(cookie.indexOf(":")+1,cookie.length);
}if(cookie.lastIndexOf(";")!=cookie.length-1){cookie+=";";
}if(cookie.indexOf("=")==0){cookie=cookie.substring(cookie.indexOf(";")+1,cookie.length);
}}else{var cookie="";
}return cookie;
}function getQueryVariable(variable){var query=location.href.split("?")[1];
if(!query){return null;
}var vars=query.split("&");
for(var i=0;
i<vars.length;
i++){var pair=vars[i].split("=");
if(pair[0]==variable){return pair[1];
}}return null;
}function realEstateAreaId(){if(typeof this.returnREAIValue=="undefined"){this.returnREAIValue="";
if(getQueryVariable("areaId")){this.returnREAIValue="areaId="+getQueryVariable("areaId")+";";
}if(typeof hs!="undefined"&&typeof hs.geo_area_id!="undefined"){geo_area_id_array=hs.geo_area_id.split(";");
for(var x=0;
x<geo_area_id_array.length;
x++){if(typeof geo_area_id_array[x]=="string"){this.returnREAIValue+="areaId="+geo_area_id_array[x]+";";
}}}}return this.returnREAIValue;
}function aptco(){var a=getQSValue("aptco");
var b=getQSValue("metro");
if(a&&b){return"aptco="+a+";metro="+b+";";
}return"";
}function locExpSponsor(){if(typeof countyName!="undefined"&&typeof stateName!="undefined"){var invalidKW=["?","=","/","\\",":",";",",","*","(",")","&","$","%","@","!","^","+"," ","[","]","{","}","."];
for(var i=0;
i<invalidKW.length;
i++){csRE=new RegExp("(\\"+invalidKW[i]+")","g");
countyName=countyName.replace(csRE,"").toLowerCase();
stateName=stateName.replace(csRE,"").toLowerCase();
}locExpKV="lexp_spon="+countyName+"-"+stateName+";";
}else{locExpKV="";
}return locExpKV;
}function realEstateCoSpon(){if(typeof _AD_TARGETING!="undefined"&&_AD_TARGETING.county&&_AD_TARGETING.state){var co_spon=_AD_TARGETING.county+"-"+_AD_TARGETING.state;
return";co_spon="+co_spon.toLowerCase().replace(/ /gi,"_").replace(/&[a-z]*(?=;)/gi,"").replace(/[^a-z\d\-\_]/gi,"")+";";
}return"";
}function front(){return"front="+((typeof commercialPageType!="undefined"&&commercialPageType=="front")?"y":"n")+";";
}wpniAds.kv={articleId:{exec:function(){if(wp_meta_data.contentType[0]==="CompoundStory"){var a=document.location.href.split("/");
return"articleId="+a[a.length-1].toLowerCase().split("_story")[0]+";";
}return"";
},check:wp_meta_data.contentType?true:false},pageId:{exec:function(){return("pageId="+wp_meta_data.page_id[0].replace(/\./g,"-")+";");
},check:wp_meta_data.page_id?true:false},front:{exec:function(){return"front="+(wp_meta_data.contentType[0]==="front"?"y":"n")+";";
},check:wp_meta_data.contentType?true:false},metakw:{exec:function(){var obj={"!c":{disaster:["plane crash","air travel","explosion","oil","war","hostage","terror","bomb","blast","mining","miner","coal","china","palin","wikileaks","death","quake","earthquake","tsunami","tornado","dead","violence","hurricane","exxon","yellowstone","montana","alaska","lisburne","prudhoe bay","anchorage","tom deruyter","deruyter","dec","department environmental conservation"],goldman:["aig","fraud","foreclosure","litton","mortgage","sec","investigation","inquiry","bonus","travel"]},kw:{energy:["energy"],re:["builder","condo","home","homeowner","housing","mortgage","property","real estate","realtor","refinance","neighborhood"]}},m=wp_meta_data.keywords.join(",").toLowerCase(),rv="",regex,key,val,len;
for(key in obj){for(val in obj[key]){regex="\\b";
len=obj[key][val].length;
while(len--){regex+=(obj[key][val][len]+"(|s|es|ed|ing)"+(len!==0?"\\b|":"")+"\\b");
}if(m.search(new RegExp(regex))!==-1){rv+=key+"="+val+";";
}}}return rv;
},check:(wp_meta_data.keywords&&(wp_meta_data.contentType&&wp_meta_data.contentType[0]!=="front"))?true:false},page:{exec:function(){return"page="+(wpniAds.contentType[wp_meta_data.contentType[0]]?wpniAds.contentType[wp_meta_data.contentType[0]]:"article")+";";
},check:wp_meta_data.contentType?true:false},redefine:function(fn,new_fn){if(typeof window[fn]!=="undefined"){window[fn]=function(){return eval(new_fn+"()");
};
return true;
}return false;
},exec:function(){var str="",key;
for(key in wpniAds.kv){if(wpniAds.kv[key].check){str+=!wpniAds.kv.redefine(key,"wpniAds.kv."+key+".exec")?wpniAds.kv[key].exec():"";
}}return str;
}};
wpniAds.kv.string=wpniAds.kv.exec();
function hackBin(_arg,currentLoc,what,delivery,onTheFly){var hackReturnValue=eval(_arg);
switch(_arg){case"onTheFly":if(what=="sponsor|rental"){hackReturnValue+=";tn=12;tr=1;tcp=0;to=v;ta=left;tva=top;";
}if(currentLoc.match("realestate")||currentLoc.match("trulia")){hackReturnValue+=realEstateCoSpon();
}if((currentLoc.match("^wiki")||currentLoc.match("innovation"))&&what.match("leaderboard")){hackReturnValue+="!category=bigleaderboard;";
}if(currentLoc=="reachwall"||currentLoc.match("/email")||currentLoc.match("admin")||currentLoc.match("/puzzles")||urlCheck("_print.html")){hackReturnValue+="!c=media;";
}if(currentLoc=="trulia"){hackReturnValue+=((what=="leaderboard")?"!c=media":(what=="flex_bb_tp")?"!c=intrusive":"")+";";
}if(commercialNode.match("washingtonpost.com")||commercialNode.match("obituaries")||commercialNode.match("weather")){hackReturnValue+="!c=intrusive;";
}hackReturnValue+=wpniAds.kv.string;
break;
case"delivery":if(delivery=="AJAX"&&what=="leaderboard"){ord_override=true;
}break;
case"what":if(what=="tiffany_tile"&&currentLoc=="metro"&&typeof jQuery!="undefined"){$(function(){$("#slug_tiffany_tile").addClass("ad-tiffany");
var tiff_tile=$("#slug_tiffany_tile");
var tiff_tile_slug=$("#slug_tiffany_tile img");
if(tiff_tile_slug&&(tiff_tile_slug.height()==60||tiff_tile_slug.height()==80)){tiff_tile.css({height:tiff_tile_slug.height()+"px",top:((tiff_tile.parent().height()-tiff_tile_slug.height())/2)+"px"});
}else{tiff_tile.css({height:"auto",top:((tiff_tile.parent().height()-tiff_tile.height())/2)+"px"});
}});
}if(what=="pushdown"&&currentLoc=="washingtonpost.com"&&navigator.userAgent.match(/msie 6/gi)){document.write('<style type="text/css">.ie.ie6 .module.ad-pushdown{ padding:0px !important }</style>');
}if(what=="336x35_top"&&currentLoc=="realestate"&&typeof commercialPageType!="undefined"&&typeof jQuery!="undefined"&&$("div#slug_336x35_top").length){$("div#slug_336x35_top").css({paddingTop:"5px"}).prepend('<div class="module advertisement-teaser fontcolor-greypurple">Advertisement</div>');
}if(what==="tiffany_tile"&&!urlCheck("allAds")){wpniAds.addScript("http://www.washingtonpost.com/wpost/js/combo?c=true&m=false&context=wp-static&r=/ad/tiffany_manager.js&r=/ad/tile_flights.js");
}break;
case"currentLoc":if(currentLoc=="metro"&&(typeof commercialPageType!=="undefined"&&commercialPageType==="front")){hackReturnValue+="/front";
}if(currentLoc.match("washingtonpost.com")&&what=="flex_bb_hp"&&location.href.match("reload=true")){hackReturnValue+="refresh";
}if(currentLoc.match("/email")||urlCheck("_print.html")||urlCheck("GA2010092907128.html")||urlCheck("GA2009012701325.html")||urlCheck("GA2010020403805.html")||urlCheck("GA2010120900367.html")){tileThatGetsDcopt=0;
}break;
}return hackReturnValue;
}var wpTiles=typeof wpTiles!=="undefined"?wpTiles:{};
wpTiles.nnHasAd=function(){if(typeof NetworkNews!=="undefined"&&typeof NetworkNews.Constants!=="undefined"){NetworkNews.Constants.hasAd=true;
}};
wpTiles.init=function(a){placeAd2(commercialNode,a,false,"");
};
if((typeof PIGGY_BACK_ALREADY_CALLED=="undefined"||!PIGGY_BACK_ALREADY_CALLED)&&!location.href.match("https://")){wpniAds.addScript("http://media.washingtonpost.com/wp-srv/javascript/piggy-back-on-ads.js");
}